# Generated by Django 4.2.1 on 2023-06-03 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('payable_amount', models.IntegerField()),
                ('paid_amount', models.IntegerField()),
                ('remaining_amount', models.IntegerField()),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
